name: Build

on:
  push:
    branches:
      - "*"
      - "!release/latest"
      - "!release/v*"

jobs:
  check_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag "${{ github.event.repository.name }}"
